package: symfony_mailer
version: '1.0.0'
author: REDAXO Team
supportpage: https://github.com/redaxo/redaxo

page:
    title: 'translate:title'
    perm: symfony_mailer[]
    pjax: true
    icon: rex-icon rex-icon-envelope
    subpages:
        config: { title: 'translate:configuration' }
        log: { title: 'translate:logging' }
        help: { title: 'translate:help', subPath: README.md, itemClass: 'pull-right' }

pages:
    system/log/mailer:
        title: Symfony-Mailer
        perm: admin

requires:
    php:
        version: '>=8.2'
    redaxo: ^5.18.1

default_config:
    from: ''
    name: 'Mailer'
    host: 'localhost'
    port: 587
    security: 'tls'
    auth: true
    username: ''
    password: ''
    charset: 'utf-8'
    logging: 0
    archive: false
    imap_archive: false
    imap_host: ''
    imap_port: 993 
    imap_username: ''
    imap_password: ''
    imap_folder: 'Sent'
