package: symfony_mailer
version: '1.0.0-beta5'
author: Friends of REDAXO 
supportpage: https://github.com/FriendsOfREDAXO/symfony_mailer/

page:
    title: 'translate:title'
    perm: symfony_mailer[]
    pjax: true
    icon: rex-icon rex-icon-envelope
    subpages:
        config: { title: 'translate:configuration' }
        queue: { title: 'translate:queue' }
        log: { title: 'translate:logging' }
        help: { title: 'translate:help', subPath: README.md, itemClass: 'pull-right' }

pages:
    system/log/mailer:
        title: Symfony-Mailer
        perm: admin

requires:
    php:
        version: '>=8.2'
    redaxo: ^5.18.1

default_config:
    transport_type: 'smtp'
    from: ''
    name: 'Mailer'
    host: 'localhost'
    port: 587
    security: 'tls'
    auth: true
    username: ''
    password: ''
    graph_tenant_id: ''
    graph_client_id: ''
    graph_client_secret: ''
    charset: 'utf-8'
    logging: 0
    archive: false
    imap_archive: false
    imap_host: ''
    imap_port: 993 
    imap_username: ''
    imap_password: ''
    imap_folder: 'INBOX.Sent'
    debug: false
    detour_mode: false
    detour_address: ''
    queue_enabled: false
    queue_batch_size: 10
    queue_max_attempts: 3
